version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  weather_api:
    build:
      context: ./app
      dockerfile: Dockerfile.api
    container_name: weather_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017/weather_data

  flask_dash_app:
    build:
      context: ./app
      dockerfile: Dockerfile.dashboard
    container_name: flask_dash_app
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - weather_api
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
